# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "test" do |node|
    node.vm.box = "bento/centos-7.1"
    node.vm.hostname = "test"
    # node.vm.network :public_network, ip: "192.168.1.4"
    node.vm.network :public_network, ip: "192.168.0.206"
    node.vm.network :forwarded_port, guest: 22, host: 2241

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "initialize/setup.yml"
      ansible.host_key_checking = false
    end

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end

    config.vm.synced_folder "synced_folder", "/vagrant"

    config.ssh.pty = true
  end
end
