# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ruby" do |node|
    node.vm.box = "bento/centos-7.2"
    node.vm.hostname = "ruby"
    node.vm.network :public_network, ip: "192.168.0.152", bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: 2253, id: "ssh"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "initialize/setup.yml"
    ansible.host_key_checking = false
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.vm.boot_timeout = 120

  config.vm.synced_folder "~/Dropbox/workspace/log4ever", "/workspace/log4ever",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant",
    rsync__exclude: ["sandbox/"]

  config.vm.synced_folder "~/Dropbox/workspace/rumble-crawler", "/workspace/rumble-crawler",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.vm.synced_folder "~/Dropbox/workspace/rumble-server", "/workspace/rumble-server",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.vm.synced_folder "~/Dropbox/workspace/rumble-notify", "/workspace/rumble-notify",
    type: "rsync",
    owner: "vagrant",
    group: "vagrant"

  config.ssh.pty = true
end
