version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
    container_name: logstash
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - elk
    ports:
      - "5044:5044"
    depends_on:
      - filebeat
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.3.1
    container_name: filebeat
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./data:/usr/share/filebeat/import_data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana
    networks:
      - elk
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge