- name: copy repository config
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/ mode=0644
- name: install elasticsearch
  yum: name=elasticsearch state=latest
- name: config settings
  replace: >-
    dest=/etc/elasticsearch/elasticsearch.yml
    regexp='{{ item.regexp }}'
    replace='{{ item.replace }}'
  with_items:
  - regexp: '#network.host:.+'
    replace: 'network.host: 0.0.0.0'
- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes
- name: wait for running elasticsearch
  wait_for: host=localhost port=9200 delay=3 timeout=300