# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "test" do |node|
    node.vm.box = "chef/centos-7.0"
    node.vm.hostname = "test"
    # node.vm.network :public_network, ip: "192.168.1.4"
    node.vm.network :public_network, ip: "192.168.0.206"
    node.vm.network :forwarded_port, guest: 22, host: 2240

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible/setup.yml"
      ansible.host_key_checking = false
    end

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end
  end
end
