---
- hosts: dev-elasticsearch
  become: yes
  user: vagrant
  roles:
    - initialize
    - java
    - elasticsearch
    - elasticsearch-plugin
    - elasticsearch-tools
    - kibana
    - filebeat
    - logstash
    - logstash-plugin
