# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ci" do |node|
    node.vm.box = "bento/centos-7.1"
    node.vm.hostname = "ci"
    # node.vm.network :public_network, ip: "192.168.1.4"
    node.vm.network :public_network, ip: "192.168.0.207", bridge: "en1: Wi-Fi (AirPort)"
    node.vm.network :forwarded_port, guest: 22, host: 2242
    node.vm.network :forwarded_port, guest: 8080, host: 8080

    config.vm.provision :ansible do |ansible|
      ansible.playbook = "initialize/setup.yml"
      ansible.host_key_checking = false
    end

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 1024]
    end

    # config.vm.synced_folder "synced_folder", "/vagrant"

    config.ssh.pty = true
  end
end
